/* Auto-generated by cbindgen — do not edit by hand. */

#ifndef OWNAUDIO_MT3_FFI_H
#define OWNAUDIO_MT3_FFI_H

/* Warning: this file is auto-generated from Rust source. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C-compatible error codes. Zero is success; everything else tells the managed layer which
 * exception to raise.
 */
typedef enum Mt3ErrorCode {
    /**
     * Operation succeeded.
     */
    Success = 0,
    /**
     * A model or vocabulary file was not at the given path.
     */
    ModelNotFound = 1,
    /**
     * ONNX Runtime refused to load the graph.
     */
    ModelLoadFailed = 2,
    /**
     * vocab.json is malformed or describes a codec we cannot decode.
     */
    VocabInvalid = 3,
    /**
     * A session ran but returned something unusable.
     */
    InferenceFailed = 4,
    /**
     * Resampling the input to the model's rate failed.
     */
    ResampleFailed = 5,
    /**
     * A required pointer argument was null.
     */
    NullPointer = 6,
    /**
     * The supplied handle does not point to a live transcriber.
     */
    InvalidHandle = 7,
    /**
     * A string argument was not valid UTF-8.
     */
    InvalidUtf8 = 8,
    /**
     * A panic was caught at the FFI boundary.
     */
    InternalPanic = 9,
    /**
     * An I/O error occurred.
     */
    IoError = 10,
} Mt3ErrorCode;

typedef struct Option_Mt3ProgressCallback Option_Mt3ProgressCallback;

/**
 * Options passed to `ownaudio_mt3_v1_create`.
 */
typedef struct NativeMt3Options {
    /**
     * ONNX Runtime intra-op threads; zero lets the runtime choose.
     */
    int32_t threads;
    /**
     * Non-zero to drop percussion before the notes come back.
     */
    int32_t skip_drums;
} NativeMt3Options;

/**
 * A loaded MT3 model — encoder, decoder pair and vocabulary.
 *
 * Never constructed on this side; the pointer handed out is really a `Box<Mt3Transcriber>`.
 */
typedef struct Mt3TranscriberHandle {
    uint8_t _private[0];
} Mt3TranscriberHandle;

/**
 * C-compatible transcribed note.
 *
 * Every field is four bytes wide on purpose — the struct then has no padding on any target we
 * build for, and the managed mirror can be a plain sequential struct. `is_drum` is an `i32`
 * rather than a bool for the same reason.
 */
typedef struct NativeMt3Note {
    /**
     * Onset in seconds.
     */
    float start_time;
    /**
     * Offset in seconds.
     */
    float end_time;
    /**
     * MIDI pitch.
     */
    int32_t pitch;
    /**
     * MIDI velocity, 1..=127.
     */
    int32_t velocity;
    /**
     * MIDI program the note was played on; zero for drums.
     */
    int32_t program;
    /**
     * Non-zero when this is a percussion hit.
     */
    int32_t is_drum;
} NativeMt3Note;

/**
 * Copies the last error message into `buffer` as NUL-terminated UTF-8.
 *
 * Returns the number of bytes that would be needed including the terminator, so a caller that
 * passed too small a buffer can retry. A null buffer only queries that length.
 *
 * # Safety
 * `buffer` must either be null or point to at least `capacity` writable bytes.
 */
size_t ownaudio_mt3_v1_last_error(char *buffer, size_t capacity);

/**
 * Loads an exported MT3 model.
 *
 * All four paths must come from the same export run. On success `out_transcriber` receives a
 * handle that must be released with [`ownaudio_mt3_v1_destroy`].
 *
 * # Safety
 * The path arguments must be NUL-terminated UTF-8 or null; `out_transcriber` must point to a
 * writable pointer slot.
 */
int32_t ownaudio_mt3_v1_create(const char *encoder_path,
                               const char *decoder_init_path,
                               const char *decoder_step_path,
                               const char *vocab_path,
                               const struct NativeMt3Options *options,
                               struct Mt3TranscriberHandle **out_transcriber);

/**
 * Releases a transcriber and the ONNX sessions behind it. Null is a no-op.
 *
 * # Safety
 * `transcriber` must have come from [`ownaudio_mt3_v1_create`] and must not be used afterwards.
 */
void ownaudio_mt3_v1_destroy(struct Mt3TranscriberHandle *transcriber);

/**
 * The sample rate the model runs at, so the caller can decode straight into it and skip a
 * resampling pass. Returns 0 for an invalid handle.
 *
 * # Safety
 * `transcriber` must be a live handle.
 */
uint32_t ownaudio_mt3_v1_sample_rate(struct Mt3TranscriberHandle *transcriber);

/**
 * Transcribes a whole track.
 *
 * `samples` is interleaved float PCM at `sample_rate`. On success `out_notes` receives an array
 * of `out_count` notes that stays valid until [`ownaudio_mt3_v1_free_notes`] is called with the
 * same pair. `progress` may be null; when it is not, it is called once per segment on the
 * calling thread.
 *
 * This runs the full autoregressive decode and takes minutes on a long track — never call it
 * from a UI or audio thread.
 *
 * # Safety
 * `samples` must point to `sample_count` readable floats; `out_notes` and `out_count` must point
 * to writable slots.
 */
int32_t ownaudio_mt3_v1_transcribe(struct Mt3TranscriberHandle *transcriber,
                                   const float *samples,
                                   size_t sample_count,
                                   uint32_t sample_rate,
                                   uint16_t channels,
                                   struct Option_Mt3ProgressCallback progress,
                                   void *user_data,
                                   struct NativeMt3Note **out_notes,
                                   size_t *out_count);

/**
 * Frees a note array handed out by [`ownaudio_mt3_v1_transcribe`].
 *
 * # Safety
 * `notes` and `count` must be exactly the pair a single transcribe call produced, and this must
 * be called at most once for that pair.
 */
void ownaudio_mt3_v1_free_notes(struct NativeMt3Note *notes, size_t count);

#endif  /* OWNAUDIO_MT3_FFI_H */
