/* Auto-generated by cbindgen — do not edit by hand. */

#ifndef OWNAUDIO_FFI_H
#define OWNAUDIO_FFI_H

/* Warning: this file is auto-generated from Rust source. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The ABI version of this native binary.
 *
 * This constant is incremented whenever a **breaking** change is made to the FFI
 * surface: adding, removing, or reordering `extern "C"` exports; changing struct
 * layouts; or renaming enum variants. Consumers (the C# managed layer) call
 * [`ownaudio_v1_get_abi_version`] at startup and reject the binary when the
 * returned value does not match the version they were compiled against.
 *
 * **Rules for incrementing:**
 * - Additive-only changes (new exports, new enum variants at the end) → no bump needed.
 * - Any breaking change → bump by 1 and update `AudioEngine.ExpectedAbiVersion` in C#.
 */
#define ABI_VERSION 1

/**
 * C-compatible error codes returned by every FFI function.
 *
 * Zero always means success.  All other values indicate failure; call
 * `ownaudio_v1_last_error_message()` on the same thread for a human-readable
 * description of the most recent error.
 */
typedef enum OwnAudioErrorCode {
    /**
     * Operation succeeded.
     */
    Success = 0,
    /**
     * No audio device matched the requested criteria.
     */
    DeviceNotFound = 1,
    /**
     * The OS audio subsystem failed to enumerate devices.
     */
    DeviceEnumerationFailed = 2,
    /**
     * The requested stream parameters are not supported by the device.
     */
    UnsupportedConfig = 3,
    /**
     * The audio stream could not be built.
     */
    StreamBuildFailed = 4,
    /**
     * Starting or stopping the stream failed.
     */
    StreamControlFailed = 5,
    /**
     * A required pointer argument was null.
     */
    NullPointer = 6,
    /**
     * The supplied handle does not point to a valid object.
     */
    InvalidHandle = 7,
    /**
     * A panic was caught inside the FFI boundary.
     */
    InternalPanic = 8,
    /**
     * An internal error not covered by the above codes.
     */
    InternalError = 9,
    /**
     * The requested host API (e.g. ASIO) is not compiled into this binary,
     * or no compatible driver is installed on this machine.
     */
    HostApiNotAvailable = 10,
    /**
     * The ASIO host API is compiled in but no ASIO driver is installed on this machine.
     */
    AsioDriverNotFound = 11,
    /**
     * The audio file could not be opened or its format could not be probed.
     */
    DecoderOpenFailed = 12,
    /**
     * No decoder backend supports the file's container or codec.
     */
    DecoderUnsupportedFormat = 13,
    /**
     * An error occurred while decoding audio data from the stream.
     */
    DecoderReadFailed = 14,
    /**
     * Seeking within the audio stream failed.
     */
    DecoderSeekFailed = 15,
} OwnAudioErrorCode;

/**
 * Sample data format used in C-facing stream configuration.
 */
typedef enum OwnAudioSampleFormat {
    /**
     * 32-bit IEEE float — recommended for DSP work.
     */
    F32 = 0,
    /**
     * Signed 16-bit integer.
     */
    I16 = 1,
    /**
     * Unsigned 16-bit integer.
     */
    U16 = 2,
} OwnAudioSampleFormat;

/**
 * Identifies the OS audio host API to use when creating an engine.
 *
 * Pass this value to `ownaudio_v1_engine_create_with_host` to select a
 * specific backend instead of the platform default.
 *
 * Not all variants are available on every platform or binary build:
 * - `Asio` requires Windows and a build compiled with `--features asio`.
 * - `CoreAudio` is only meaningful on macOS.
 * - `Alsa` is only meaningful on Linux.
 *
 * Requesting an unavailable variant returns
 * [`OwnAudioErrorCode::HostApiNotAvailable`] (10) or
 * [`OwnAudioErrorCode::AsioDriverNotFound`] (11); the call never panics.
 */
typedef enum OwnHostApi {
    /**
     * Windows Audio Session API — the default Windows audio backend.
     */
    Wasapi = 0,
    /**
     * Steinberg ASIO — low-latency Windows audio for professional interfaces.
     * Requires `--features asio` at build time and an installed ASIO driver.
     */
    Asio = 1,
    /**
     * Apple Core Audio — the default macOS audio backend.
     */
    CoreAudio = 2,
    /**
     * Advanced Linux Sound Architecture — the default Linux audio backend.
     */
    Alsa = 3,
} OwnHostApi;

/**
 * Opaque handle to a streaming audio file decoder.
 *
 * Create with `ownaudio_v1_decoder_open`; release with
 * `ownaudio_v1_decoder_destroy`.
 */
typedef struct OwnAudioDecoderHandle {
    uint8_t _private[0];
} OwnAudioDecoderHandle;

/**
 * C-compatible mirror of [`ownaudio_core::AudioStreamInfo`], returned by value.
 *
 * Layout matches the core struct exactly (both are `#[repr(C)]`).
 */
typedef struct OwnAudioStreamInfo {
    /**
     * Number of interleaved channels in the decoded output.
     */
    uint32_t channels;
    /**
     * Output sample rate in Hz.
     */
    uint32_t sample_rate;
    /**
     * Total duration in milliseconds; `u64::MAX` if unknown.
     */
    uint64_t duration_ms;
    /**
     * Source bit depth, or `0` for float/compressed formats.
     */
    uint32_t bit_depth;
} OwnAudioStreamInfo;

/**
 * Snapshot descriptor of an audio device, passed to the C# caller.
 *
 * The `name` field is a null-terminated UTF-8 string allocated by Rust.
 * The caller must **not** free `name` directly.  Pass the entire array to
 * `ownaudio_v1_free_device_list` when done.
 */
typedef struct OwnAudioDeviceInfo {
    /**
     * Human-readable device name (null-terminated UTF-8, Rust-owned).
     */
    const char *name;
    /**
     * Whether this device is the current system default for input.
     */
    bool is_default_input;
    /**
     * Whether this device is the current system default for output.
     */
    bool is_default_output;
    /**
     * Maximum number of input channels supported by this device.
     */
    uint16_t max_input_channels;
    /**
     * Maximum number of output channels supported by this device.
     */
    uint16_t max_output_channels;
    /**
     * The device's preferred sample rate in Hz.
     */
    uint32_t default_sample_rate;
} OwnAudioDeviceInfo;

/**
 * Opaque handle to a [`MultiTrackMixer`] instance.
 *
 * Create with `ownaudio_v1_mixer_create`; release with `ownaudio_v1_mixer_destroy`.
 */
typedef struct OwnAudioMixerHandle {
    uint8_t _private[0];
} OwnAudioMixerHandle;

/**
 * Opaque handle to a single audio [`Track`] inside a mixer.
 *
 * Create with `ownaudio_v1_track_create`; release with `ownaudio_v1_track_destroy`.
 */
typedef struct OwnAudioTrackHandle {
    uint8_t _private[0];
} OwnAudioTrackHandle;

/**
 * Opaque handle to an audio effect inside a track's effect chain.
 *
 * Create with `ownaudio_v1_track_add_effect`; release with `ownaudio_v1_effect_destroy`.
 */
typedef struct OwnAudioEffectHandle {
    uint8_t _private[0];
} OwnAudioEffectHandle;

/**
 * Planar audio buffer passed to the plugin's process callback.
 *
 * Binary-compatible with the `AudioBufferC` struct in the `OwnAudioVst` native
 * host (`ownvst3_exports.h`): two arrays of channel pointers plus the channel
 * and sample counts. `inputs` and `outputs` point at arrays of `num_channels`
 * `f32*` planes, each holding `num_samples` samples.
 */
typedef struct VstAudioBuffer {
    /**
     * Array of `num_channels` input channel pointers (planar `f32`).
     */
    float **inputs;
    /**
     * Array of `num_channels` output channel pointers (planar `f32`).
     */
    float **outputs;
    /**
     * Number of channels addressed by `inputs` / `outputs`.
     */
    int32_t num_channels;
    /**
     * Number of samples per channel plane.
     */
    int32_t num_samples;
} VstAudioBuffer;

/**
 * Nullable C ABI process callback exported by the `OwnAudioVst` native host
 * (`VST3Plugin_ProcessAudio`), as it crosses the FFI boundary.
 *
 * Receives the opaque plugin handle and a pointer to a [`VstAudioBuffer`],
 * processes one block in place into `outputs`, and returns `true` on success.
 * Modelled as an `Option` so the C# side can (in principle) pass a null pointer;
 * the FFI layer rejects that before an effect is ever built.
 *
 * # Safety
 * Invoked on the audio thread. The callee must be real-time safe (no heap
 * allocation, no blocking) and the `handle` must remain valid for the entire
 * lifetime of the owning [`VstEffect`].
 */
typedef bool (*VstProcessFn)(void *handle, struct VstAudioBuffer *buffer);

/**
 * Opaque handle to the control side of a file-backed track source.
 *
 * Create with `ownaudio_v1_track_open_file`; release with
 * `ownaudio_v1_file_source_destroy`.  The decoded audio is produced entirely on
 * the native prefetch thread, so — unlike [`OwnAudioTrackSourceHandle`] — the
 * control thread never pushes samples; it only toggles looping, polls the
 * end-of-stream latch and requests seeks.
 */
typedef struct OwnAudioFileSourceHandle {
    uint8_t _private[0];
} OwnAudioFileSourceHandle;

/**
 * Opaque handle to the write side of a track's audio-feed ring buffer.
 *
 * Create with `ownaudio_v1_track_set_ring_source`; release with
 * `ownaudio_v1_track_source_destroy`.  The matching read side is owned by the
 * track on the audio thread, so the control thread pushes decoded samples
 * through this handle without ever touching the mixer.
 */
typedef struct OwnAudioTrackSourceHandle {
    uint8_t _private[0];
} OwnAudioTrackSourceHandle;

/**
 * Opaque handle to an [`AudioEngine`] instance.
 *
 * The C# side holds this as `IntPtr`.  Create with
 * `ownaudio_v1_engine_create`; release with `ownaudio_v1_engine_destroy`.
 */
typedef struct OwnAudioEngineHandle {
    uint8_t _private[0];
} OwnAudioEngineHandle;

/**
 * Parameters for opening an audio stream, passed across the FFI boundary.
 *
 * `buffer_size_frames = 0` means "let the engine choose the platform default".
 * Any non-zero value requests a specific buffer size.
 */
typedef struct OwnAudioStreamConfig {
    /**
     * Target sample rate in Hz (e.g. 44100, 48000).
     */
    uint32_t sample_rate;
    /**
     * Number of channels (1 = mono, 2 = stereo).
     */
    uint16_t channels;
    /**
     * Sample data format.
     */
    enum OwnAudioSampleFormat sample_format;
    /**
     * Requested buffer size in audio frames; 0 uses the platform default.
     */
    uint32_t buffer_size_frames;
} OwnAudioStreamConfig;

/**
 * Function pointer the C# side provides for output streams.
 *
 * Called on the audio real-time thread for every buffer.
 * - `buffer` — interleaved f32 samples; the callback must fill all
 *   `frame_count * channels` elements.
 * - `frame_count` — number of audio frames in this buffer.
 * - `channels` — number of interleaved channels.
 * - `user_data` — the opaque pointer supplied at stream creation, passed
 *   back unchanged on every call.
 *
 * # Safety
 * The callback must be real-time safe: no heap allocation, no blocking I/O,
 * no non-RT-safe locks.  `user_data` must remain valid for the entire
 * lifetime of the stream and must be safe to access from the audio thread.
 */
typedef void (*OwnAudioOutputCallback)(float *buffer,
                                       size_t frame_count,
                                       uint16_t channels,
                                       void *user_data);

/**
 * Opaque handle to an output audio stream.
 *
 * Create with `ownaudio_v1_open_output_stream`; release with
 * `ownaudio_v1_output_stream_destroy`.
 */
typedef struct OwnAudioOutputStreamHandle {
    uint8_t _private[0];
} OwnAudioOutputStreamHandle;

/**
 * Function pointer the C# side provides for input streams.
 *
 * Called on the audio real-time thread for every captured buffer.
 * - `buffer` — read-only interleaved f32 samples.
 *
 * Same lifetime and real-time constraints as [`OwnAudioOutputCallback`].
 */
typedef void (*OwnAudioInputCallback)(const float *buffer,
                                      size_t frame_count,
                                      uint16_t channels,
                                      void *user_data);

/**
 * Opaque handle to an input audio stream.
 *
 * Create with `ownaudio_v1_open_input_stream`; release with
 * `ownaudio_v1_input_stream_destroy`.
 */
typedef struct OwnAudioInputStreamHandle {
    uint8_t _private[0];
} OwnAudioInputStreamHandle;

/**
 * Returns the last error message as a null-terminated UTF-8 string, or null
 * if no error has been recorded on this thread.
 *
 * # Lifetime
 * The pointer is valid until the next FFI call on this thread that sets an
 * error, or until the thread exits.  The caller must **not** free it.
 */
const char *ownaudio_v1_last_error_message(void);

/**
 * Returns the ABI version of this native binary.
 *
 * The C# wrapper calls this function immediately after loading the library and
 * compares the result to its compile-time constant. If the versions differ it
 * raises `AbiVersionMismatchException` so the user gets a clear error instead of
 * a cryptic access violation.
 *
 * Returns [`ABI_VERSION`] — always `1` for the initial v1 ABI surface.
 */
uint32_t ownaudio_v1_get_abi_version(void);

/**
 * Returns a null-terminated UTF-8 string describing the package version baked
 * into this binary at compile time (e.g. `"1.0.0"` or `"1.2.0-ci.42"`).
 *
 * The pointer is valid for the lifetime of the process.  The caller must **not**
 * free it.  The string is derived from `version.json` at build time via `build.rs`.
 */
const char *ownaudio_v1_get_package_version(void);

/**
 * Opens an audio file for streaming decoding and writes the handle to
 * `*out_decoder`.
 *
 * - `path` — null-terminated UTF-8 file path.
 * - `target_sample_rate` — desired output sample rate in Hz; `0` keeps source.
 * - `target_channels` — desired output channel count; `0` keeps source.
 * - `prefetch_seconds` — prefetch buffer length in seconds; `<= 0` uses 2.0.
 * - `out_decoder` — receives the new decoder handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.  The handle must be
 * released with `ownaudio_v1_decoder_destroy`.
 */
int32_t ownaudio_v1_decoder_open(const char *path,
                                 uint32_t target_sample_rate,
                                 uint32_t target_channels,
                                 float prefetch_seconds,
                                 struct OwnAudioDecoderHandle **out_decoder);

/**
 * Reads up to `buffer_count` decoded interleaved `f32` samples into `buffer`
 * and writes the number actually produced to `*out_samples_written`.
 *
 * Real-time safe: never blocks or allocates.  A value smaller than
 * `buffer_count` means EOF or a transient prefetch underrun.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_decoder_read(struct OwnAudioDecoderHandle *handle,
                                 float *buffer,
                                 size_t buffer_count,
                                 size_t *out_samples_written);

/**
 * Requests a non-blocking seek to `frame_position` (output sample frames).
 *
 * The prefetch thread performs the seek asynchronously; subsequent reads may
 * briefly return pre-seek samples already buffered in the ring.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_decoder_seek(struct OwnAudioDecoderHandle *handle, uint64_t frame_position);

/**
 * Writes the decoded output stream metadata to `*out_info`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_decoder_get_stream_info(struct OwnAudioDecoderHandle *handle,
                                            struct OwnAudioStreamInfo *out_info);

/**
 * Writes `true` to `*out_is_eof` when the file has been fully decoded and the
 * prefetch buffer is drained.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_decoder_is_eof(struct OwnAudioDecoderHandle *handle, bool *out_is_eof);

/**
 * Destroys a decoder handle, stopping and joining the prefetch thread.
 *
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_decoder_destroy(struct OwnAudioDecoderHandle *handle);

/**
 * Lists all available output devices on the default host.
 *
 * On success, `*out_devices` points to a Rust-owned array of
 * `*out_count` elements.  The caller must release it with
 * `ownaudio_v1_free_device_list(*out_devices, *out_count)`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_list_output_devices(struct OwnAudioDeviceInfo **out_devices, size_t *out_count);

/**
 * Lists all available input devices on the default host.
 *
 * On success, `*out_devices` points to a Rust-owned array of
 * `*out_count` elements.  The caller must release it with
 * `ownaudio_v1_free_device_list(*out_devices, *out_count)`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_list_input_devices(struct OwnAudioDeviceInfo **out_devices, size_t *out_count);

/**
 * Releases an array previously returned by `ownaudio_v1_list_output_devices`
 * or `ownaudio_v1_list_input_devices`.
 *
 * Passing `null` or `count = 0` is safe and has no effect.
 */
void ownaudio_v1_free_device_list(struct OwnAudioDeviceInfo *devices, size_t count);

/**
 * Adds a new effect of the given type to the track's effect chain.
 *
 * - `mixer` — valid mixer handle (required to reach the track).
 * - `track` — valid track handle.
 * - `effect_type` — numeric effect type identifier (`EffectType` enum value).
 * - `sample_rate` — sample rate in Hz; used to size internal buffers.
 * - `out_effect` — receives the new effect handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 * Returns `OwnAudioErrorCode::InvalidHandle` (7) for an unknown `effect_type`.
 */
int32_t ownaudio_v1_track_add_effect(struct OwnAudioMixerHandle *mixer,
                                     struct OwnAudioTrackHandle *track,
                                     uint32_t effect_type,
                                     float sample_rate,
                                     struct OwnAudioEffectHandle **out_effect);

/**
 * Adds a new effect of the given type to the mixer's **master** effect chain,
 * which runs once over the fully summed mix after every track is rendered.
 *
 * - `mixer` — valid mixer handle.
 * - `effect_type` — numeric effect type identifier (`EffectType` enum value).
 * - `sample_rate` — sample rate in Hz; used to size internal buffers.
 * - `out_effect` — receives the new effect handle on success.
 *
 * The returned handle is controlled with the same
 * `ownaudio_v1_effect_set_param` / `_get_param` / `_remove` / `_destroy` calls as
 * track effects — it simply targets the master chain instead of a track.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 * Returns `OwnAudioErrorCode::InvalidHandle` (7) for an unknown `effect_type`.
 */
int32_t ownaudio_v1_mixer_add_master_effect(struct OwnAudioMixerHandle *mixer,
                                            uint32_t effect_type,
                                            float sample_rate,
                                            struct OwnAudioEffectHandle **out_effect);

/**
 * Removes a master effect from the mixer's master chain and destroys the handle.
 *
 * The master counterpart of [`ownaudio_v1_effect_remove`]: it takes no track
 * handle because master effects are not owned by any track.
 *
 * - `mixer` — valid mixer handle.
 * - `effect` — valid master effect handle from `ownaudio_v1_mixer_add_master_effect`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_mixer_remove_master_effect(struct OwnAudioMixerHandle *mixer,
                                               struct OwnAudioEffectHandle *effect);

/**
 * Adds an external VST3 plugin to a track's effect chain as a native effect.
 *
 * The plugin is created, loaded and parameter-controlled entirely on the C#
 * control plane (the `OwnAudioVst` host); this only receives the opaque plugin
 * handle and the host's `VST3Plugin_ProcessAudio` function pointer, and calls
 * it on the audio thread for every block — no linking against the host and no
 * managed audio processing.
 *
 * - `mixer` — valid mixer handle (required to reach the track).
 * - `track` — valid track handle.
 * - `plugin_handle` — opaque plugin instance handle owned by the caller. It
 *   MUST outlive this effect (remove/destroy the effect before freeing it).
 * - `process_fn` — the host's `VST3Plugin_ProcessAudio` pointer; must not be null.
 * - `max_channels` — largest channel count the chain will present (planar
 *   scratch is sized for this).
 * - `max_block_size` — largest block size in samples per channel.
 * - `latency_samples` — the plugin's processing latency in frames, reported to
 *   the mixer for plugin delay compensation (0 when the plugin is zero-latency).
 * - `out_effect` — receives the new effect handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_add_vst_effect(struct OwnAudioMixerHandle *mixer,
                                         struct OwnAudioTrackHandle *track,
                                         void *plugin_handle,
                                         VstProcessFn process_fn,
                                         uint16_t max_channels,
                                         uint32_t max_block_size,
                                         uint32_t latency_samples,
                                         struct OwnAudioEffectHandle **out_effect);

/**
 * Adds an external VST3 plugin to the mixer's **master** effect chain, which
 * runs once over the fully summed mix after every track is rendered.
 *
 * The master counterpart of [`ownaudio_v1_track_add_vst_effect`]; the returned
 * handle is controlled with the same `ownaudio_v1_effect_set_param` /
 * `_get_param` / `ownaudio_v1_mixer_remove_master_effect` calls as any master
 * effect. See that function for the argument contract.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_mixer_add_master_vst_effect(struct OwnAudioMixerHandle *mixer,
                                                void *plugin_handle,
                                                VstProcessFn process_fn,
                                                uint16_t max_channels,
                                                uint32_t max_block_size,
                                                uint32_t latency_samples,
                                                struct OwnAudioEffectHandle **out_effect);

/**
 * Destroys an effect handle.
 *
 * Passing `null` is safe and has no effect.
 * The effect is NOT removed from the track chain; call `ownaudio_v1_effect_remove` first.
 */
void ownaudio_v1_effect_destroy(struct OwnAudioEffectHandle *effect);

/**
 * Removes the effect from its track's effect chain and destroys the handle.
 *
 * - `mixer` — valid mixer handle.
 * - `track` — valid track handle.
 * - `effect` — valid effect handle to remove and destroy.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_effect_remove(struct OwnAudioMixerHandle *mixer,
                                  struct OwnAudioTrackHandle *track,
                                  struct OwnAudioEffectHandle *effect);

/**
 * Sets a parameter on an effect by numeric identifier.
 *
 * - `effect` — valid effect handle.
 * - `param_id` — numeric parameter identifier (effect-specific).
 * - `value` — new parameter value; clamped to the valid range silently.
 *
 * Returns `OwnAudioErrorCode::Success` (0) when the parameter is recognised.
 * Returns `OwnAudioErrorCode::InvalidHandle` (7) when `param_id` is unknown.
 */
int32_t ownaudio_v1_effect_set_param(struct OwnAudioMixerHandle *mixer,
                                     struct OwnAudioEffectHandle *effect,
                                     uint32_t param_id,
                                     float value);

/**
 * Reads the current value of an effect parameter.
 *
 * - `effect` — valid effect handle.
 * - `param_id` — numeric parameter identifier.
 * - `out_value` — receives the current value on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) when the parameter is recognised.
 * Returns `OwnAudioErrorCode::InvalidHandle` (7) when `param_id` is unknown.
 */
int32_t ownaudio_v1_effect_get_param(struct OwnAudioMixerHandle *mixer,
                                     struct OwnAudioEffectHandle *effect,
                                     uint32_t param_id,
                                     float *out_value);

/**
 * Opens `path`, installs a decoding source on `track`, and writes the control
 * handle to `*out_source`.
 *
 * The file is decoded (and resampled/remixed) to `target_sample_rate` /
 * `target_channels` on a dedicated native prefetch thread, then fed straight
 * into the track on the audio thread — no managed pump is involved.  Looping
 * and end-of-stream are handled natively; observe them through the returned
 * handle.
 *
 * - `mixer` — valid mixer handle that owns the track.
 * - `track` — valid track handle whose source is to be installed.
 * - `path` — null-terminated UTF-8 file path.
 * - `target_sample_rate` — desired output sample rate in Hz; `0` keeps source.
 * - `target_channels` — desired output channel count; `0` keeps source.
 * - `prefetch_frames` — ring-buffer capacity in sample frames; `0` uses a
 *   sensible default (about two seconds at 44.1 kHz).
 * - `out_source` — receives the control handle on success.
 *
 * The source is installed through the mixer's lock-free command queue, so it
 * becomes the track's source on the next render block; any previous source is
 * retired off the audio thread.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.  Destroy the returned
 * handle with `ownaudio_v1_file_source_destroy` after the track's source has
 * been cleared or the track removed.
 */
int32_t ownaudio_v1_track_open_file(struct OwnAudioMixerHandle *mixer,
                                    struct OwnAudioTrackHandle *track,
                                    const char *path,
                                    uint32_t target_sample_rate,
                                    uint32_t target_channels,
                                    size_t prefetch_frames,
                                    struct OwnAudioFileSourceHandle **out_source);

/**
 * Enables or disables seamless looping for a file source.
 *
 * When enabled, reaching end-of-stream rewinds the decoder to the start and
 * keeps playing; when disabled, end-of-stream latches the finished flag.
 *
 * - `source` — valid handle from `ownaudio_v1_track_open_file`.
 * - `enabled` — non-zero to loop, zero to stop at end-of-stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_file_source_set_loop(struct OwnAudioFileSourceHandle *source, uint8_t enabled);

/**
 * Writes whether the file source has reached end-of-stream (without looping) to
 * `*out_finished` (`1` = finished, `0` = still playing or looping).
 *
 * The flag latches at end-of-stream and clears as soon as audio flows again
 * after a seek.  Poll it from the control thread to raise a completion event.
 *
 * - `source` — valid handle from `ownaudio_v1_track_open_file`.
 * - `out_finished` — receives the finished flag on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_file_source_is_finished(struct OwnAudioFileSourceHandle *source,
                                            uint8_t *out_finished);

/**
 * Requests a seek to `frame_position` (output frames) on a file source.
 *
 * Non-blocking: the native prefetch thread repositions the decoder on its next
 * iteration and the finished latch clears once audio flows from the new
 * position.  Divide a time in seconds by nothing — pass the target expressed in
 * output frames (`seconds * sample_rate`).
 *
 * - `source` — valid handle from `ownaudio_v1_track_open_file`.
 * - `frame_position` — target position in output sample frames.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_file_source_seek(struct OwnAudioFileSourceHandle *source,
                                     uint64_t frame_position);

/**
 * Destroys a file-source control handle.
 *
 * Passing `null` is safe and has no effect.  Dropping this handle only releases
 * the control block; the decoding source itself lives on the audio thread until
 * the track's source is cleared (`ownaudio_v1_track_clear_source`) or the track
 * is removed, at which point the source and its prefetch thread are retired off
 * the real-time path.
 */
void ownaudio_v1_file_source_destroy(struct OwnAudioFileSourceHandle *source);

/**
 * Creates a lock-free ring buffer feeding the track and writes the write-side
 * handle to `*out_source`.
 *
 * - `mixer` — valid mixer handle that owns the track.
 * - `track` — valid track handle whose source is to be (re)installed.
 * - `capacity_samples` — fixed ring-buffer capacity in interleaved `f32`
 *   samples; sized for the desired buffering latency
 *   (`sample_rate * channels * latency_seconds`).  Clamped up to 1.
 * - `out_source` — receives the write-side handle on success.
 *
 * The reader is installed through the mixer's lock-free command queue, so it
 * becomes the track's source on the next render block; any previous source is
 * retired off the audio thread.  Samples written before the reader is installed
 * are buffered and played once it is — the ring buffer is live immediately.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.  Destroy the returned
 * handle with `ownaudio_v1_track_source_destroy`.
 */
int32_t ownaudio_v1_track_set_ring_source(struct OwnAudioMixerHandle *mixer,
                                          struct OwnAudioTrackHandle *track,
                                          size_t capacity_samples,
                                          struct OwnAudioTrackSourceHandle **out_source);

/**
 * Pushes up to `sample_count` interleaved `f32` samples into the track feed and
 * writes the number actually accepted to `*out_written`.
 *
 * Lock-free and non-blocking: when the ring buffer is full, fewer samples (or
 * zero) are written and the caller must retry later (back-pressure).  Use
 * [`ownaudio_v1_track_source_free_samples`] to size writes against the free
 * space.
 *
 * - `source` — valid handle from `ownaudio_v1_track_set_ring_source`.
 * - `samples` — pointer to the first of `sample_count` `f32` samples.
 * - `sample_count` — number of samples available at `samples`.
 * - `out_written` — receives the number of samples accepted.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_source_write(struct OwnAudioTrackSourceHandle *source,
                                       const float *samples,
                                       size_t sample_count,
                                       size_t *out_written);

/**
 * Writes the number of samples that can currently be written without overflow
 * to `*out_free`.
 *
 * - `source` — valid handle from `ownaudio_v1_track_set_ring_source`.
 * - `out_free` — receives the free-sample count.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_source_free_samples(struct OwnAudioTrackSourceHandle *source,
                                              size_t *out_free);

/**
 * Clears a track's audio source, silencing it.
 *
 * The current source (if any) is retired off the audio thread on the next
 * render block.  Any [`OwnAudioTrackSourceHandle`] previously returned for this
 * track keeps writing into a now-detached ring buffer until it is destroyed;
 * callers should destroy the stale source handle after clearing.
 *
 * - `mixer` — valid mixer handle that owns the track.
 * - `track` — valid track handle whose source is to be cleared.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_clear_source(struct OwnAudioMixerHandle *mixer,
                                       struct OwnAudioTrackHandle *track);

/**
 * Destroys a track-source write handle and releases its ring-buffer producer.
 *
 * Passing `null` is safe and has no effect.  Dropping the producer does not
 * disturb the track's reader on the audio thread; the track simply underruns
 * (renders silence) once the buffered samples are consumed.
 */
void ownaudio_v1_track_source_destroy(struct OwnAudioTrackSourceHandle *source);

/**
 * Creates a new `AudioEngine` instance and writes its handle to `*out_handle`.
 *
 * The handle must be released with `ownaudio_v1_engine_destroy` when no
 * longer needed.  A single engine can be used to open multiple streams.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_engine_create(struct OwnAudioEngineHandle **out_handle);

/**
 * Creates a new `AudioEngine` instance using an explicitly chosen host API, and writes
 * its handle to `*out_handle`.
 *
 * - `host_api` — the audio host API to use (e.g. `OwnHostApi::Asio`).
 *   Pass `OwnHostApi::Wasapi` / `OwnHostApi::CoreAudio` / `OwnHostApi::Alsa`
 *   to request the standard platform backend without relying on the compile-time default.
 * - `out_handle` — receives the new engine handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 * Returns `OwnAudioErrorCode::HostApiNotAvailable` (10) when the requested
 * host API is not compiled into this binary.
 * Returns `OwnAudioErrorCode::AsioDriverNotFound` (11) when ASIO is compiled
 * in but no ASIO driver is installed on this machine.
 *
 * If `out_handle` is null returns `OwnAudioErrorCode::NullPointer` (6).
 */
int32_t ownaudio_v1_engine_create_with_host(enum OwnHostApi host_api,
                                            struct OwnAudioEngineHandle **out_handle);

/**
 * Destroys an engine handle created by `ownaudio_v1_engine_create`.
 *
 * All streams opened from this engine must be destroyed before calling this
 * function.  Passing `null` is safe and has no effect.
 */
void ownaudio_v1_engine_destroy(struct OwnAudioEngineHandle *handle);

/**
 * Opens an output stream and writes its handle to `*out_stream`.
 *
 * - `engine` — a valid handle returned by `ownaudio_v1_engine_create`.
 * - `device_name` — null-terminated UTF-8 name of the target device, or
 *   `null` to use the system default output device.
 * - `config` — pointer to a filled `OwnAudioStreamConfig`; must not be null.
 * - `callback` — function called on the audio thread for every buffer;
 *   must not be null.
 * - `user_data` — opaque pointer passed back to `callback`; may be null.
 * - `out_stream` — receives the new stream handle on success.
 *
 * The stream starts in the paused state; call
 * `ownaudio_v1_output_stream_play` to begin audio output.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_open_output_stream(struct OwnAudioEngineHandle *engine,
                                       const char *device_name,
                                       const struct OwnAudioStreamConfig *config,
                                       OwnAudioOutputCallback callback,
                                       void *user_data,
                                       struct OwnAudioOutputStreamHandle **out_stream);

/**
 * Opens an output stream **driven by a multi-track mixer** and writes its
 * handle to `*out_stream`.
 *
 * Unlike `ownaudio_v1_open_output_stream` (which calls back into C# for every
 * buffer), this moves the mixer onto the cpal audio thread: on every callback
 * the stream calls [`MultiTrackMixer::mix`], which drains the lock-free command
 * queue and renders all active tracks — no per-buffer P/Invoke, no GC, no
 * cross-thread data race.
 *
 * - `engine` — a valid handle returned by `ownaudio_v1_engine_create`.
 * - `mixer` — a valid handle returned by `ownaudio_v1_mixer_create`; its
 *   sample rate and channel count should match `config`.
 * - `device_name` — null-terminated UTF-8 device name, or `null` for the
 *   system default output device.
 * - `config` — pointer to a filled `OwnAudioStreamConfig`; must not be null.
 * - `out_stream` — receives the new stream handle on success.
 *
 * The mixer is consumed: after this call the mixer handle keeps working for
 * structural changes and parameter access (via its command queue), but the
 * mixer can no longer be attached to another stream.  Calling this twice on the
 * same mixer returns `OwnAudioErrorCode::InvalidHandle`.
 *
 * The stream starts paused; call `ownaudio_v1_output_stream_play` to begin
 * output.  Destroy the stream before destroying the mixer.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 *
 * [`MultiTrackMixer::mix`]: ownaudio_core::MultiTrackMixer::mix
 */
int32_t ownaudio_v1_mixer_open_output_stream(struct OwnAudioEngineHandle *engine,
                                             struct OwnAudioMixerHandle *mixer,
                                             const char *device_name,
                                             const struct OwnAudioStreamConfig *config,
                                             struct OwnAudioOutputStreamHandle **out_stream);

/**
 * Starts (or resumes) audio output on the given stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_output_stream_play(struct OwnAudioOutputStreamHandle *stream);

/**
 * Pauses audio output without destroying the stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_output_stream_pause(struct OwnAudioOutputStreamHandle *stream);

/**
 * Destroys an output stream and releases all associated resources.
 *
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_output_stream_destroy(struct OwnAudioOutputStreamHandle *stream);

/**
 * Opens an input stream and writes its handle to `*out_stream`.
 *
 * - `device_name` — null-terminated UTF-8 name of the target device, or
 *   `null` to use the system default input device.
 * - `callback` — called on the audio thread with each captured buffer.
 *
 * The stream starts in the paused state; call
 * `ownaudio_v1_input_stream_play` to begin capturing.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_open_input_stream(struct OwnAudioEngineHandle *engine,
                                      const char *device_name,
                                      const struct OwnAudioStreamConfig *config,
                                      OwnAudioInputCallback callback,
                                      void *user_data,
                                      struct OwnAudioInputStreamHandle **out_stream);

/**
 * Starts (or resumes) audio capture on the given stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_input_stream_play(struct OwnAudioInputStreamHandle *stream);

/**
 * Pauses audio capture without destroying the stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_input_stream_pause(struct OwnAudioInputStreamHandle *stream);

/**
 * Destroys an input stream and releases all associated resources.
 *
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_input_stream_destroy(struct OwnAudioInputStreamHandle *stream);

/**
 * Creates a new [`MultiTrackMixer`] and writes its handle to `*out_mixer`.
 *
 * - `sample_rate` — output sample rate in Hz.
 * - `channels` — number of output channels (1 = mono, 2 = stereo).
 * - `out_mixer` — receives the new mixer handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_mixer_create(float sample_rate,
                                 uint16_t channels,
                                 struct OwnAudioMixerHandle **out_mixer);

/**
 * Destroys a mixer handle and releases all associated resources.
 *
 * Passing `null` is safe and has no effect.
 * All track and effect handles obtained from this mixer must be destroyed
 * before calling this function.
 */
void ownaudio_v1_mixer_destroy(struct OwnAudioMixerHandle *mixer);

/**
 * Starts every track in the mixer in a single call, against the shared clock.
 *
 * Sets all tracks to the playing state from the control thread in one
 * operation, so they begin on the same audio callback — a sample-accurate
 * start that avoids the per-track P/Invoke round-trips and the synchronisation
 * drift they would introduce.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_mixer_play_all(struct OwnAudioMixerHandle *mixer);

/**
 * Pauses every track in the mixer in a single call, against the shared clock.
 *
 * Sets all tracks to the paused state from the control thread in one
 * operation, so they pause on the same audio callback — avoiding the per-track
 * P/Invoke round-trips and the synchronisation drift they would introduce.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_mixer_pause_all(struct OwnAudioMixerHandle *mixer);

/**
 * Stops every track in the mixer in a single call, against the shared clock.
 *
 * Sets all tracks to the stopped state from the control thread in one
 * operation, so they stop on the same audio callback — avoiding the per-track
 * P/Invoke round-trips and the synchronisation drift they would introduce.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_mixer_stop_all(struct OwnAudioMixerHandle *mixer);

/**
 * Adds a new track to the mixer and writes its handle to `*out_track`.
 *
 * - `mixer` — valid mixer handle.
 * - `out_track` — receives the new track handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_create(struct OwnAudioMixerHandle *mixer,
                                 struct OwnAudioTrackHandle **out_track);

/**
 * Destroys a track handle.  Does NOT remove the track from the mixer.
 *
 * Call `ownaudio_v1_track_remove` first to remove the track from the mix,
 * then this function to release the handle memory.
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_track_destroy(struct OwnAudioTrackHandle *track);

/**
 * Removes and destroys the track from the mixer.
 *
 * The track handle is invalidated after this call; do not use it afterwards.
 * Passing `null` is safe and has no effect.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_remove(struct OwnAudioMixerHandle *mixer,
                                 struct OwnAudioTrackHandle *track);

/**
 * Starts or resumes playback of the track.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_play(struct OwnAudioTrackHandle *track);

/**
 * Pauses the track without resetting its position.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_pause(struct OwnAudioTrackHandle *track);

/**
 * Stops the track and resets its position to zero.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_stop(struct OwnAudioTrackHandle *track);

/**
 * Sets the track's playback position to `sample_position`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_seek(struct OwnAudioTrackHandle *track, uint64_t _sample_position);

/**
 * Writes the number of output frames the track has rendered since the last
 * position reset to `*out_frames`.
 *
 * This is the track's authoritative *rendered* playback position: it is
 * advanced on the audio thread by the mixer as each block is produced, and lags
 * the *fed* position by the ring-buffer depth. Divide by the sample rate to get
 * the position in seconds.
 *
 * - `track` — valid track handle.
 * - `out_frames` — receives the rendered frame count on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_get_rendered_frames(struct OwnAudioTrackHandle *track,
                                              uint64_t *out_frames);

/**
 * Resets the track's rendered-frame position counter to zero.
 *
 * Call this from the control thread after seeking the track's source (in the
 * intermediate phase the decoder seek happens on the C# side), so the rendered
 * position restarts from the seek target.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_reset_position(struct OwnAudioTrackHandle *track);

/**
 * Sets the track gain (linear amplitude multiplier; 1.0 = unity).
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_set_gain(struct OwnAudioTrackHandle *track, float gain);

/**
 * Sets the track tempo ratio (1.0 = normal speed, 2.0 = double speed).
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_set_tempo(struct OwnAudioTrackHandle *track, float ratio);

/**
 * Sets the track pitch shift in semitones (-24 … +24).
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_set_pitch(struct OwnAudioTrackHandle *track, float semitones);

/**
 * Sets the track mute state (0.0 = unmuted, 1.0 = muted).
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_set_mute(struct OwnAudioTrackHandle *track, float muted);

#endif  /* OWNAUDIO_FFI_H */
