/* Auto-generated by cbindgen — do not edit by hand. */

#ifndef OWNAUDIO_FFI_H
#define OWNAUDIO_FFI_H

/* Warning: this file is auto-generated from Rust source. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * C-compatible error codes returned by every FFI function.
 *
 * Zero always means success.  All other values indicate failure; call
 * `ownaudio_v1_last_error_message()` on the same thread for a human-readable
 * description of the most recent error.
 */
typedef enum OwnAudioErrorCode {
    /**
     * Operation succeeded.
     */
    Success = 0,
    /**
     * No audio device matched the requested criteria.
     */
    DeviceNotFound = 1,
    /**
     * The OS audio subsystem failed to enumerate devices.
     */
    DeviceEnumerationFailed = 2,
    /**
     * The requested stream parameters are not supported by the device.
     */
    UnsupportedConfig = 3,
    /**
     * The audio stream could not be built.
     */
    StreamBuildFailed = 4,
    /**
     * Starting or stopping the stream failed.
     */
    StreamControlFailed = 5,
    /**
     * A required pointer argument was null.
     */
    NullPointer = 6,
    /**
     * The supplied handle does not point to a valid object.
     */
    InvalidHandle = 7,
    /**
     * A panic was caught inside the FFI boundary.
     */
    InternalPanic = 8,
    /**
     * An internal error not covered by the above codes.
     */
    InternalError = 9,
} OwnAudioErrorCode;

/**
 * Sample data format used in C-facing stream configuration.
 */
typedef enum OwnAudioSampleFormat {
    /**
     * 32-bit IEEE float — recommended for DSP work.
     */
    F32 = 0,
    /**
     * Signed 16-bit integer.
     */
    I16 = 1,
    /**
     * Unsigned 16-bit integer.
     */
    U16 = 2,
} OwnAudioSampleFormat;

/**
 * Snapshot descriptor of an audio device, passed to the C# caller.
 *
 * The `name` field is a null-terminated UTF-8 string allocated by Rust.
 * The caller must **not** free `name` directly.  Pass the entire array to
 * `ownaudio_v1_free_device_list` when done.
 */
typedef struct OwnAudioDeviceInfo {
    /**
     * Human-readable device name (null-terminated UTF-8, Rust-owned).
     */
    const char *name;
    /**
     * Whether this device is the current system default for input.
     */
    bool is_default_input;
    /**
     * Whether this device is the current system default for output.
     */
    bool is_default_output;
    /**
     * Maximum number of input channels supported by this device.
     */
    uint16_t max_input_channels;
    /**
     * Maximum number of output channels supported by this device.
     */
    uint16_t max_output_channels;
    /**
     * The device's preferred sample rate in Hz.
     */
    uint32_t default_sample_rate;
} OwnAudioDeviceInfo;

/**
 * Opaque handle to an [`AudioEngine`] instance.
 *
 * The C# side holds this as `IntPtr`.  Create with
 * `ownaudio_v1_engine_create`; release with `ownaudio_v1_engine_destroy`.
 */
typedef struct OwnAudioEngineHandle {
    uint8_t _private[0];
} OwnAudioEngineHandle;

/**
 * Parameters for opening an audio stream, passed across the FFI boundary.
 *
 * `buffer_size_frames = 0` means "let the engine choose the platform default".
 * Any non-zero value requests a specific buffer size.
 */
typedef struct OwnAudioStreamConfig {
    /**
     * Target sample rate in Hz (e.g. 44100, 48000).
     */
    uint32_t sample_rate;
    /**
     * Number of channels (1 = mono, 2 = stereo).
     */
    uint16_t channels;
    /**
     * Sample data format.
     */
    enum OwnAudioSampleFormat sample_format;
    /**
     * Requested buffer size in audio frames; 0 uses the platform default.
     */
    uint32_t buffer_size_frames;
} OwnAudioStreamConfig;

/**
 * Function pointer the C# side provides for output streams.
 *
 * Called on the audio real-time thread for every buffer.
 * - `buffer` — interleaved f32 samples; the callback must fill all
 *   `frame_count * channels` elements.
 * - `frame_count` — number of audio frames in this buffer.
 * - `channels` — number of interleaved channels.
 * - `user_data` — the opaque pointer supplied at stream creation, passed
 *   back unchanged on every call.
 *
 * # Safety
 * The callback must be real-time safe: no heap allocation, no blocking I/O,
 * no non-RT-safe locks.  `user_data` must remain valid for the entire
 * lifetime of the stream and must be safe to access from the audio thread.
 */
typedef void (*OwnAudioOutputCallback)(float *buffer,
                                       size_t frame_count,
                                       uint16_t channels,
                                       void *user_data);

/**
 * Opaque handle to an output audio stream.
 *
 * Create with `ownaudio_v1_open_output_stream`; release with
 * `ownaudio_v1_output_stream_destroy`.
 */
typedef struct OwnAudioOutputStreamHandle {
    uint8_t _private[0];
} OwnAudioOutputStreamHandle;

/**
 * Function pointer the C# side provides for input streams.
 *
 * Called on the audio real-time thread for every captured buffer.
 * - `buffer` — read-only interleaved f32 samples.
 *
 * Same lifetime and real-time constraints as [`OwnAudioOutputCallback`].
 */
typedef void (*OwnAudioInputCallback)(const float *buffer,
                                      size_t frame_count,
                                      uint16_t channels,
                                      void *user_data);

/**
 * Opaque handle to an input audio stream.
 *
 * Create with `ownaudio_v1_open_input_stream`; release with
 * `ownaudio_v1_input_stream_destroy`.
 */
typedef struct OwnAudioInputStreamHandle {
    uint8_t _private[0];
} OwnAudioInputStreamHandle;

/**
 * Returns the last error message as a null-terminated UTF-8 string, or null
 * if no error has been recorded on this thread.
 *
 * # Lifetime
 * The pointer is valid until the next FFI call on this thread that sets an
 * error, or until the thread exits.  The caller must **not** free it.
 */
const char *ownaudio_v1_last_error_message(void);

/**
 * Lists all available output devices on the default host.
 *
 * On success, `*out_devices` points to a Rust-owned array of
 * `*out_count` elements.  The caller must release it with
 * `ownaudio_v1_free_device_list(*out_devices, *out_count)`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_list_output_devices(struct OwnAudioDeviceInfo **out_devices, size_t *out_count);

/**
 * Lists all available input devices on the default host.
 *
 * On success, `*out_devices` points to a Rust-owned array of
 * `*out_count` elements.  The caller must release it with
 * `ownaudio_v1_free_device_list(*out_devices, *out_count)`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_list_input_devices(struct OwnAudioDeviceInfo **out_devices, size_t *out_count);

/**
 * Releases an array previously returned by `ownaudio_v1_list_output_devices`
 * or `ownaudio_v1_list_input_devices`.
 *
 * Passing `null` or `count = 0` is safe and has no effect.
 */
void ownaudio_v1_free_device_list(struct OwnAudioDeviceInfo *devices, size_t count);

/**
 * Creates a new `AudioEngine` instance and writes its handle to `*out_handle`.
 *
 * The handle must be released with `ownaudio_v1_engine_destroy` when no
 * longer needed.  A single engine can be used to open multiple streams.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_engine_create(struct OwnAudioEngineHandle **out_handle);

/**
 * Destroys an engine handle created by `ownaudio_v1_engine_create`.
 *
 * All streams opened from this engine must be destroyed before calling this
 * function.  Passing `null` is safe and has no effect.
 */
void ownaudio_v1_engine_destroy(struct OwnAudioEngineHandle *handle);

/**
 * Opens an output stream and writes its handle to `*out_stream`.
 *
 * - `engine` — a valid handle returned by `ownaudio_v1_engine_create`.
 * - `device_name` — null-terminated UTF-8 name of the target device, or
 *   `null` to use the system default output device.
 * - `config` — pointer to a filled `OwnAudioStreamConfig`; must not be null.
 * - `callback` — function called on the audio thread for every buffer;
 *   must not be null.
 * - `user_data` — opaque pointer passed back to `callback`; may be null.
 * - `out_stream` — receives the new stream handle on success.
 *
 * The stream starts in the paused state; call
 * `ownaudio_v1_output_stream_play` to begin audio output.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_open_output_stream(struct OwnAudioEngineHandle *engine,
                                       const char *device_name,
                                       const struct OwnAudioStreamConfig *config,
                                       OwnAudioOutputCallback callback,
                                       void *user_data,
                                       struct OwnAudioOutputStreamHandle **out_stream);

/**
 * Starts (or resumes) audio output on the given stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_output_stream_play(struct OwnAudioOutputStreamHandle *stream);

/**
 * Pauses audio output without destroying the stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_output_stream_pause(struct OwnAudioOutputStreamHandle *stream);

/**
 * Destroys an output stream and releases all associated resources.
 *
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_output_stream_destroy(struct OwnAudioOutputStreamHandle *stream);

/**
 * Opens an input stream and writes its handle to `*out_stream`.
 *
 * - `device_name` — null-terminated UTF-8 name of the target device, or
 *   `null` to use the system default input device.
 * - `callback` — called on the audio thread with each captured buffer.
 *
 * The stream starts in the paused state; call
 * `ownaudio_v1_input_stream_play` to begin capturing.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_open_input_stream(struct OwnAudioEngineHandle *engine,
                                      const char *device_name,
                                      const struct OwnAudioStreamConfig *config,
                                      OwnAudioInputCallback callback,
                                      void *user_data,
                                      struct OwnAudioInputStreamHandle **out_stream);

/**
 * Starts (or resumes) audio capture on the given stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_input_stream_play(struct OwnAudioInputStreamHandle *stream);

/**
 * Pauses audio capture without destroying the stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_input_stream_pause(struct OwnAudioInputStreamHandle *stream);

/**
 * Destroys an input stream and releases all associated resources.
 *
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_input_stream_destroy(struct OwnAudioInputStreamHandle *stream);

#endif  /* OWNAUDIO_FFI_H */
