/* Auto-generated by cbindgen — do not edit by hand. */

#ifndef OWNAUDIO_FFI_H
#define OWNAUDIO_FFI_H

/* Warning: this file is auto-generated from Rust source. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * The ABI version of this native binary.
 *
 * This constant is incremented whenever a **breaking** change is made to the FFI
 * surface: adding, removing, or reordering `extern "C"` exports; changing struct
 * layouts; or renaming enum variants. Consumers (the C# managed layer) call
 * [`ownaudio_v1_get_abi_version`] at startup and reject the binary when the
 * returned value does not match the version they were compiled against.
 *
 * **Rules for incrementing:**
 * - Additive-only changes (new exports, new enum variants at the end) → no bump needed.
 * - Any breaking change → bump by 1 and update `AudioEngine.ExpectedAbiVersion` in C#.
 */
#define ABI_VERSION 1

/**
 * C-compatible error codes returned by every FFI function.
 *
 * Zero always means success.  All other values indicate failure; call
 * `ownaudio_v1_last_error_message()` on the same thread for a human-readable
 * description of the most recent error.
 */
typedef enum OwnAudioErrorCode {
    /**
     * Operation succeeded.
     */
    Success = 0,
    /**
     * No audio device matched the requested criteria.
     */
    DeviceNotFound = 1,
    /**
     * The OS audio subsystem failed to enumerate devices.
     */
    DeviceEnumerationFailed = 2,
    /**
     * The requested stream parameters are not supported by the device.
     */
    UnsupportedConfig = 3,
    /**
     * The audio stream could not be built.
     */
    StreamBuildFailed = 4,
    /**
     * Starting or stopping the stream failed.
     */
    StreamControlFailed = 5,
    /**
     * A required pointer argument was null.
     */
    NullPointer = 6,
    /**
     * The supplied handle does not point to a valid object.
     */
    InvalidHandle = 7,
    /**
     * A panic was caught inside the FFI boundary.
     */
    InternalPanic = 8,
    /**
     * An internal error not covered by the above codes.
     */
    InternalError = 9,
    /**
     * The requested host API (e.g. ASIO) is not compiled into this binary,
     * or no compatible driver is installed on this machine.
     */
    HostApiNotAvailable = 10,
    /**
     * The ASIO host API is compiled in but no ASIO driver is installed on this machine.
     */
    AsioDriverNotFound = 11,
} OwnAudioErrorCode;

/**
 * Sample data format used in C-facing stream configuration.
 */
typedef enum OwnAudioSampleFormat {
    /**
     * 32-bit IEEE float — recommended for DSP work.
     */
    F32 = 0,
    /**
     * Signed 16-bit integer.
     */
    I16 = 1,
    /**
     * Unsigned 16-bit integer.
     */
    U16 = 2,
} OwnAudioSampleFormat;

/**
 * Identifies the OS audio host API to use when creating an engine.
 *
 * Pass this value to `ownaudio_v1_engine_create_with_host` to select a
 * specific backend instead of the platform default.
 *
 * Not all variants are available on every platform or binary build:
 * - `Asio` requires Windows and a build compiled with `--features asio`.
 * - `CoreAudio` is only meaningful on macOS.
 * - `Alsa` is only meaningful on Linux.
 *
 * Requesting an unavailable variant returns
 * [`OwnAudioErrorCode::HostApiNotAvailable`] (10) or
 * [`OwnAudioErrorCode::AsioDriverNotFound`] (11); the call never panics.
 */
typedef enum OwnHostApi {
    /**
     * Windows Audio Session API — the default Windows audio backend.
     */
    Wasapi = 0,
    /**
     * Steinberg ASIO — low-latency Windows audio for professional interfaces.
     * Requires `--features asio` at build time and an installed ASIO driver.
     */
    Asio = 1,
    /**
     * Apple Core Audio — the default macOS audio backend.
     */
    CoreAudio = 2,
    /**
     * Advanced Linux Sound Architecture — the default Linux audio backend.
     */
    Alsa = 3,
} OwnHostApi;

/**
 * Snapshot descriptor of an audio device, passed to the C# caller.
 *
 * The `name` field is a null-terminated UTF-8 string allocated by Rust.
 * The caller must **not** free `name` directly.  Pass the entire array to
 * `ownaudio_v1_free_device_list` when done.
 */
typedef struct OwnAudioDeviceInfo {
    /**
     * Human-readable device name (null-terminated UTF-8, Rust-owned).
     */
    const char *name;
    /**
     * Whether this device is the current system default for input.
     */
    bool is_default_input;
    /**
     * Whether this device is the current system default for output.
     */
    bool is_default_output;
    /**
     * Maximum number of input channels supported by this device.
     */
    uint16_t max_input_channels;
    /**
     * Maximum number of output channels supported by this device.
     */
    uint16_t max_output_channels;
    /**
     * The device's preferred sample rate in Hz.
     */
    uint32_t default_sample_rate;
} OwnAudioDeviceInfo;

/**
 * Opaque handle to a [`MultiTrackMixer`] instance.
 *
 * Create with `ownaudio_v1_mixer_create`; release with `ownaudio_v1_mixer_destroy`.
 */
typedef struct OwnAudioMixerHandle {
    uint8_t _private[0];
} OwnAudioMixerHandle;

/**
 * Opaque handle to a single audio [`Track`] inside a mixer.
 *
 * Create with `ownaudio_v1_track_create`; release with `ownaudio_v1_track_destroy`.
 */
typedef struct OwnAudioTrackHandle {
    uint8_t _private[0];
} OwnAudioTrackHandle;

/**
 * Opaque handle to an audio effect inside a track's effect chain.
 *
 * Create with `ownaudio_v1_track_add_effect`; release with `ownaudio_v1_effect_destroy`.
 */
typedef struct OwnAudioEffectHandle {
    uint8_t _private[0];
} OwnAudioEffectHandle;

/**
 * Opaque handle to an [`AudioEngine`] instance.
 *
 * The C# side holds this as `IntPtr`.  Create with
 * `ownaudio_v1_engine_create`; release with `ownaudio_v1_engine_destroy`.
 */
typedef struct OwnAudioEngineHandle {
    uint8_t _private[0];
} OwnAudioEngineHandle;

/**
 * Parameters for opening an audio stream, passed across the FFI boundary.
 *
 * `buffer_size_frames = 0` means "let the engine choose the platform default".
 * Any non-zero value requests a specific buffer size.
 */
typedef struct OwnAudioStreamConfig {
    /**
     * Target sample rate in Hz (e.g. 44100, 48000).
     */
    uint32_t sample_rate;
    /**
     * Number of channels (1 = mono, 2 = stereo).
     */
    uint16_t channels;
    /**
     * Sample data format.
     */
    enum OwnAudioSampleFormat sample_format;
    /**
     * Requested buffer size in audio frames; 0 uses the platform default.
     */
    uint32_t buffer_size_frames;
} OwnAudioStreamConfig;

/**
 * Function pointer the C# side provides for output streams.
 *
 * Called on the audio real-time thread for every buffer.
 * - `buffer` — interleaved f32 samples; the callback must fill all
 *   `frame_count * channels` elements.
 * - `frame_count` — number of audio frames in this buffer.
 * - `channels` — number of interleaved channels.
 * - `user_data` — the opaque pointer supplied at stream creation, passed
 *   back unchanged on every call.
 *
 * # Safety
 * The callback must be real-time safe: no heap allocation, no blocking I/O,
 * no non-RT-safe locks.  `user_data` must remain valid for the entire
 * lifetime of the stream and must be safe to access from the audio thread.
 */
typedef void (*OwnAudioOutputCallback)(float *buffer,
                                       size_t frame_count,
                                       uint16_t channels,
                                       void *user_data);

/**
 * Opaque handle to an output audio stream.
 *
 * Create with `ownaudio_v1_open_output_stream`; release with
 * `ownaudio_v1_output_stream_destroy`.
 */
typedef struct OwnAudioOutputStreamHandle {
    uint8_t _private[0];
} OwnAudioOutputStreamHandle;

/**
 * Function pointer the C# side provides for input streams.
 *
 * Called on the audio real-time thread for every captured buffer.
 * - `buffer` — read-only interleaved f32 samples.
 *
 * Same lifetime and real-time constraints as [`OwnAudioOutputCallback`].
 */
typedef void (*OwnAudioInputCallback)(const float *buffer,
                                      size_t frame_count,
                                      uint16_t channels,
                                      void *user_data);

/**
 * Opaque handle to an input audio stream.
 *
 * Create with `ownaudio_v1_open_input_stream`; release with
 * `ownaudio_v1_input_stream_destroy`.
 */
typedef struct OwnAudioInputStreamHandle {
    uint8_t _private[0];
} OwnAudioInputStreamHandle;

/**
 * Returns the last error message as a null-terminated UTF-8 string, or null
 * if no error has been recorded on this thread.
 *
 * # Lifetime
 * The pointer is valid until the next FFI call on this thread that sets an
 * error, or until the thread exits.  The caller must **not** free it.
 */
const char *ownaudio_v1_last_error_message(void);

/**
 * Returns the ABI version of this native binary.
 *
 * The C# wrapper calls this function immediately after loading the library and
 * compares the result to its compile-time constant. If the versions differ it
 * raises `AbiVersionMismatchException` so the user gets a clear error instead of
 * a cryptic access violation.
 *
 * Returns [`ABI_VERSION`] — always `1` for the initial v1 ABI surface.
 */
uint32_t ownaudio_v1_get_abi_version(void);

/**
 * Returns a null-terminated UTF-8 string describing the package version baked
 * into this binary at compile time (e.g. `"1.0.0"` or `"1.2.0-ci.42"`).
 *
 * The pointer is valid for the lifetime of the process.  The caller must **not**
 * free it.  The string is derived from `version.json` at build time via `build.rs`.
 */
const char *ownaudio_v1_get_package_version(void);

/**
 * Lists all available output devices on the default host.
 *
 * On success, `*out_devices` points to a Rust-owned array of
 * `*out_count` elements.  The caller must release it with
 * `ownaudio_v1_free_device_list(*out_devices, *out_count)`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_list_output_devices(struct OwnAudioDeviceInfo **out_devices, size_t *out_count);

/**
 * Lists all available input devices on the default host.
 *
 * On success, `*out_devices` points to a Rust-owned array of
 * `*out_count` elements.  The caller must release it with
 * `ownaudio_v1_free_device_list(*out_devices, *out_count)`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_list_input_devices(struct OwnAudioDeviceInfo **out_devices, size_t *out_count);

/**
 * Releases an array previously returned by `ownaudio_v1_list_output_devices`
 * or `ownaudio_v1_list_input_devices`.
 *
 * Passing `null` or `count = 0` is safe and has no effect.
 */
void ownaudio_v1_free_device_list(struct OwnAudioDeviceInfo *devices, size_t count);

/**
 * Adds a new effect of the given type to the track's effect chain.
 *
 * - `mixer` — valid mixer handle (required to reach the track).
 * - `track` — valid track handle.
 * - `effect_type` — numeric effect type identifier (`EffectType` enum value).
 * - `sample_rate` — sample rate in Hz; used to size internal buffers.
 * - `out_effect` — receives the new effect handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 * Returns `OwnAudioErrorCode::InvalidHandle` (7) for an unknown `effect_type`.
 */
int32_t ownaudio_v1_track_add_effect(struct OwnAudioMixerHandle *mixer,
                                     struct OwnAudioTrackHandle *track,
                                     uint32_t effect_type,
                                     float sample_rate,
                                     struct OwnAudioEffectHandle **out_effect);

/**
 * Destroys an effect handle.
 *
 * Passing `null` is safe and has no effect.
 * The effect is NOT removed from the track chain; call `ownaudio_v1_effect_remove` first.
 */
void ownaudio_v1_effect_destroy(struct OwnAudioEffectHandle *effect);

/**
 * Removes the effect from its track's effect chain and destroys the handle.
 *
 * - `mixer` — valid mixer handle.
 * - `track` — valid track handle.
 * - `effect` — valid effect handle to remove and destroy.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_effect_remove(struct OwnAudioMixerHandle *mixer,
                                  struct OwnAudioTrackHandle *track,
                                  struct OwnAudioEffectHandle *effect);

/**
 * Sets a parameter on an effect by numeric identifier.
 *
 * - `effect` — valid effect handle.
 * - `param_id` — numeric parameter identifier (effect-specific).
 * - `value` — new parameter value; clamped to the valid range silently.
 *
 * Returns `OwnAudioErrorCode::Success` (0) when the parameter is recognised.
 * Returns `OwnAudioErrorCode::InvalidHandle` (7) when `param_id` is unknown.
 */
int32_t ownaudio_v1_effect_set_param(struct OwnAudioMixerHandle *mixer,
                                     struct OwnAudioEffectHandle *effect,
                                     uint32_t param_id,
                                     float value);

/**
 * Reads the current value of an effect parameter.
 *
 * - `effect` — valid effect handle.
 * - `param_id` — numeric parameter identifier.
 * - `out_value` — receives the current value on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) when the parameter is recognised.
 * Returns `OwnAudioErrorCode::InvalidHandle` (7) when `param_id` is unknown.
 */
int32_t ownaudio_v1_effect_get_param(struct OwnAudioMixerHandle *mixer,
                                     struct OwnAudioEffectHandle *effect,
                                     uint32_t param_id,
                                     float *out_value);

/**
 * Creates a new `AudioEngine` instance and writes its handle to `*out_handle`.
 *
 * The handle must be released with `ownaudio_v1_engine_destroy` when no
 * longer needed.  A single engine can be used to open multiple streams.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_engine_create(struct OwnAudioEngineHandle **out_handle);

/**
 * Creates a new `AudioEngine` instance using an explicitly chosen host API, and writes
 * its handle to `*out_handle`.
 *
 * - `host_api` — the audio host API to use (e.g. `OwnHostApi::Asio`).
 *   Pass `OwnHostApi::Wasapi` / `OwnHostApi::CoreAudio` / `OwnHostApi::Alsa`
 *   to request the standard platform backend without relying on the compile-time default.
 * - `out_handle` — receives the new engine handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 * Returns `OwnAudioErrorCode::HostApiNotAvailable` (10) when the requested
 * host API is not compiled into this binary.
 * Returns `OwnAudioErrorCode::AsioDriverNotFound` (11) when ASIO is compiled
 * in but no ASIO driver is installed on this machine.
 *
 * If `out_handle` is null returns `OwnAudioErrorCode::NullPointer` (6).
 */
int32_t ownaudio_v1_engine_create_with_host(enum OwnHostApi host_api,
                                            struct OwnAudioEngineHandle **out_handle);

/**
 * Destroys an engine handle created by `ownaudio_v1_engine_create`.
 *
 * All streams opened from this engine must be destroyed before calling this
 * function.  Passing `null` is safe and has no effect.
 */
void ownaudio_v1_engine_destroy(struct OwnAudioEngineHandle *handle);

/**
 * Opens an output stream and writes its handle to `*out_stream`.
 *
 * - `engine` — a valid handle returned by `ownaudio_v1_engine_create`.
 * - `device_name` — null-terminated UTF-8 name of the target device, or
 *   `null` to use the system default output device.
 * - `config` — pointer to a filled `OwnAudioStreamConfig`; must not be null.
 * - `callback` — function called on the audio thread for every buffer;
 *   must not be null.
 * - `user_data` — opaque pointer passed back to `callback`; may be null.
 * - `out_stream` — receives the new stream handle on success.
 *
 * The stream starts in the paused state; call
 * `ownaudio_v1_output_stream_play` to begin audio output.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_open_output_stream(struct OwnAudioEngineHandle *engine,
                                       const char *device_name,
                                       const struct OwnAudioStreamConfig *config,
                                       OwnAudioOutputCallback callback,
                                       void *user_data,
                                       struct OwnAudioOutputStreamHandle **out_stream);

/**
 * Starts (or resumes) audio output on the given stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_output_stream_play(struct OwnAudioOutputStreamHandle *stream);

/**
 * Pauses audio output without destroying the stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_output_stream_pause(struct OwnAudioOutputStreamHandle *stream);

/**
 * Destroys an output stream and releases all associated resources.
 *
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_output_stream_destroy(struct OwnAudioOutputStreamHandle *stream);

/**
 * Opens an input stream and writes its handle to `*out_stream`.
 *
 * - `device_name` — null-terminated UTF-8 name of the target device, or
 *   `null` to use the system default input device.
 * - `callback` — called on the audio thread with each captured buffer.
 *
 * The stream starts in the paused state; call
 * `ownaudio_v1_input_stream_play` to begin capturing.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_open_input_stream(struct OwnAudioEngineHandle *engine,
                                      const char *device_name,
                                      const struct OwnAudioStreamConfig *config,
                                      OwnAudioInputCallback callback,
                                      void *user_data,
                                      struct OwnAudioInputStreamHandle **out_stream);

/**
 * Starts (or resumes) audio capture on the given stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_input_stream_play(struct OwnAudioInputStreamHandle *stream);

/**
 * Pauses audio capture without destroying the stream.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_input_stream_pause(struct OwnAudioInputStreamHandle *stream);

/**
 * Destroys an input stream and releases all associated resources.
 *
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_input_stream_destroy(struct OwnAudioInputStreamHandle *stream);

/**
 * Creates a new [`MultiTrackMixer`] and writes its handle to `*out_mixer`.
 *
 * - `sample_rate` — output sample rate in Hz.
 * - `channels` — number of output channels (1 = mono, 2 = stereo).
 * - `out_mixer` — receives the new mixer handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_mixer_create(float sample_rate,
                                 uint16_t channels,
                                 struct OwnAudioMixerHandle **out_mixer);

/**
 * Destroys a mixer handle and releases all associated resources.
 *
 * Passing `null` is safe and has no effect.
 * All track and effect handles obtained from this mixer must be destroyed
 * before calling this function.
 */
void ownaudio_v1_mixer_destroy(struct OwnAudioMixerHandle *mixer);

/**
 * Adds a new track to the mixer and writes its handle to `*out_track`.
 *
 * - `mixer` — valid mixer handle.
 * - `out_track` — receives the new track handle on success.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_create(struct OwnAudioMixerHandle *mixer,
                                 struct OwnAudioTrackHandle **out_track);

/**
 * Destroys a track handle.  Does NOT remove the track from the mixer.
 *
 * Call `ownaudio_v1_track_remove` first to remove the track from the mix,
 * then this function to release the handle memory.
 * Passing `null` is safe and has no effect.
 */
void ownaudio_v1_track_destroy(struct OwnAudioTrackHandle *track);

/**
 * Removes and destroys the track from the mixer.
 *
 * The track handle is invalidated after this call; do not use it afterwards.
 * Passing `null` is safe and has no effect.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_remove(struct OwnAudioMixerHandle *mixer,
                                 struct OwnAudioTrackHandle *track);

/**
 * Starts or resumes playback of the track.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_play(struct OwnAudioTrackHandle *track);

/**
 * Pauses the track without resetting its position.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_pause(struct OwnAudioTrackHandle *track);

/**
 * Stops the track and resets its position to zero.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_stop(struct OwnAudioTrackHandle *track);

/**
 * Sets the track's playback position to `sample_position`.
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_seek(struct OwnAudioTrackHandle *track, uint64_t _sample_position);

/**
 * Sets the track gain (linear amplitude multiplier; 1.0 = unity).
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_set_gain(struct OwnAudioTrackHandle *track, float gain);

/**
 * Sets the track tempo ratio (1.0 = normal speed, 2.0 = double speed).
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_set_tempo(struct OwnAudioTrackHandle *track, float ratio);

/**
 * Sets the track pitch shift in semitones (-24 … +24).
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_set_pitch(struct OwnAudioTrackHandle *track, float semitones);

/**
 * Sets the track mute state (0.0 = unmuted, 1.0 = muted).
 *
 * Returns `OwnAudioErrorCode::Success` (0) on success.
 */
int32_t ownaudio_v1_track_set_mute(struct OwnAudioTrackHandle *track, float muted);

#endif  /* OWNAUDIO_FFI_H */
