using System;
using System.Runtime.InteropServices;

namespace Ownaudio.Native.RustAudio.Interop;

/// <summary>
/// Mirrors the <c>OwnHostApi</c> enum from <c>ownaudio_ffi.h</c>.
/// Values must match exactly — generated by cbindgen from Rust source.
/// </summary>
internal enum NativeHostApi : int
{
    /// <summary>Windows Audio Session API — the default Windows audio backend.</summary>
    Wasapi = 0,

    /// <summary>Steinberg ASIO — requires <c>--features asio</c> and an installed driver.</summary>
    Asio = 1,

    /// <summary>Apple Core Audio — the default macOS audio backend.</summary>
    CoreAudio = 2,

    /// <summary>Advanced Linux Sound Architecture — the default Linux audio backend.</summary>
    Alsa = 3,
}

internal static unsafe partial class OwnAudioNative
{
    #region Host API engine creation

    /// <summary>
    /// Creates a new audio engine using an explicitly chosen host API and writes its handle
    /// to <paramref name="outHandle"/>.
    /// </summary>
    /// <param name="hostApi">The audio host API to use.</param>
    /// <param name="outHandle">
    /// Receives the new engine handle on success.  Must be released with
    /// <see cref="ownaudio_v1_engine_destroy"/>.
    /// </param>
    /// <returns>
    /// <see cref="NativeErrorCode.Success"/> (0) on success;
    /// <see cref="NativeErrorCode.HostApiNotAvailable"/> (10) when the requested host API
    /// is not compiled in or not available on this platform;
    /// <see cref="NativeErrorCode.AsioDriverNotFound"/> (11) when ASIO is compiled in but
    /// no ASIO driver is installed.
    /// </returns>
    /// <remarks>
    /// Mirrors: <c>ownaudio_v1_engine_create_with_host(OwnHostApi, OwnAudioEngineHandle**) → i32</c>
    /// </remarks>
    [LibraryImport(NativeLibraryLoader.LogicalName)]
    internal static partial int ownaudio_v1_engine_create_with_host(
        NativeHostApi hostApi,
        out IntPtr outHandle);

    #endregion
}
